#NumPy Important Methods

In [3]:
import numpy as np

In [7]:
# shape - Returns the dimensions of the array (rows, columns).
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)   # Output: (2, 3)

(2, 3)


In [9]:
# dtype - Returns the data type of the elements in the array.
arr = np.array([1, 2, 3])
print(arr.dtype)   # Output: int64 (or int32 based on system)

int32


In [15]:
# ndim - Returns the number of dimensions in the array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)    # Output: 2

2


In [17]:
# size - Returns the total number of elements in the array.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)    # Output: 6

6


In [19]:
# reshape - Changes the shape of the array without changing its data.
arr = np.array([1, 2, 3, 4, 5, 6])
arr_reshaped = arr.reshape(2, 3)
print(arr_reshaped)  
# Output: [[1, 2, 3], [4, 5, 6]]

[[1 2 3]
 [4 5 6]]


In [21]:
# arange - Creates an array with a range of numbers.
arr = np.arange(0, 10, 2)   # Start at 0, end before 10, step by 2
print(arr)                  # Output: [0, 2, 4, 6, 8]

[0 2 4 6 8]


In [31]:
# linspace - Creates an array with evenly spaced values over a specified interval.
arr = np.linspace(0, 1, 5)  # 5 values between 0 and 1
print(arr)                  # Output: [0. , 0.25, 0.5 , 0.75, 1. ]


[0.   0.25 0.5  0.75 1.  ]


In [33]:
# min, max, argmin, argmax - Returns minimum, maximum, and their indices in the array.
arr = np.array([10, 20, 5, 30])
print(arr.min())            # Output: 5
print(arr.max())            # Output: 30
print(arr.argmin())         # Output: 2 (index of min value)
print(arr.argmax())         # Output: 3 (index of max value)

5
30
2
3


In [35]:
# sum and mean - Calculates the sum and mean (average) of array elements.
arr = np.array([1, 2, 3, 4, 5])
print(arr.sum())            # Output: 15
print(arr.mean())           # Output: 3.0

15
3.0


In [37]:
# std and var - Returns the standard deviation and variance of array elements.
arr = np.array([1, 2, 3, 4, 5])
print(arr.std())            # Output: 1.4142135623730951
print(arr.var())            # Output: 2.0

1.4142135623730951
2.0


In [39]:
# transpose - Transposes rows and columns in a 2D array.
arr = np.array([[1, 2], [3, 4]])
print(arr.transpose())      # Output: [[1, 3], [2, 4]]

[[1 3]
 [2 4]]


In [47]:
# flatten - Converts a multi-dimensional array into a 1D array.
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.flatten())        # Output: [1, 2, 3, 4, 5, 6, 7, 8, 9]

[1 2 3 4 5 6 7 8 9]


In [49]:
# unique - Finds the unique elements of an array.
arr = np.array([1, 2, 2, 3, 4, 4, 5])
print(np.unique(arr))       # Output: [1, 2, 3, 4, 5]

[1 2 3 4 5]


In [51]:
# concatenate - Joins two or more arrays along a specified axis.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))   # Output: [1, 2, 3, 4, 5, 6]

[1 2 3 4 5 6]


In [53]:
# zeros, ones, and full - Creates arrays of zeros, ones, or a specified constant.
print(np.zeros((2, 2)))     # 2x2 array of zeros
print(np.ones((3, 3)))      # 3x3 array of ones
print(np.full((2, 2), 7))   # 2x2 array filled with 7

[[0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]


In [55]:
# eye - Creates an identity matrix.
print(np.eye(3))            # Output: 3x3 identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
# dot - Computes the dot product of two arrays.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))         # Output: 32 (1*4 + 2*5 + 3*6)

32


In [61]:
# random.rand, random.randn, and random.randint - Generates random values.
print(np.random.rand(3))            # 1D array with 3 random numbers between 0 and 1
print(np.random.randn(3))           # 1D array with 3 normally distributed random numbers
print(np.random.randint(1, 10, 5))  # 1D array of 5 random integers between 1 and 10

[0.22590134 0.82039894 0.75676058]
[ 0.87331353 -1.20169701  1.15440062]
[2 3 1 4 2]


In [63]:
# where - Returns indices where a specified condition is true.
arr = np.array([1, 2, 3, 4, 5])
print(np.where(arr > 3))    # Output: (array([3, 4]),) -> indices where condition is true

(array([3, 4], dtype=int64),)


In [65]:
# cumsum and cumprod - Cumulative sum and cumulative product.
arr = np.array([1, 2, 3, 4])
print(np.cumsum(arr))       # Output: [ 1  3  6 10]
print(np.cumprod(arr))      # Output: [ 1  2  6 24]

[ 1  3  6 10]
[ 1  2  6 24]
