In [3]:
import numpy as np

In [3]:
# 1D Array
arr1d = np.array([1, 2, 3, 4, 5])
# 2D Array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
# Addition, subtraction, multiplication, division
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)      # Element-wise addition
print(a - b)      # Element-wise subtraction
print(a * b)      # Element-wise multiplication
print(a / b)      # Element-wise division

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [17]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.shape)         # Shape of array (rows, columns)
print(arr.ndim)          # Number of dimensions
print(arr.size)          # Total number of elements
print(arr.dtype)         # Data type of elements


(3, 3)
2
9
int32


In [35]:
arr1 = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
arr_reshaped = arr1.reshape(2, 6)  # Reshape to 2 rows and 3 columns
print(arr_reshaped)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [37]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2[0])             # First element
print(arr2[1:4])           # Elements from index 1 to 3

1
[2 3 4]


In [39]:
print(arr2[-3])

3


In [41]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(np.mean(data))      # Mean
print(np.median(data))    # Median
print(np.std(data))       # Standard deviation
print(np.var(data))       # Variance
print(np.max(data))       # Maximum value
print(np.min(data))       # Minimum value

5.5
5.5
2.8722813232690143
8.25
10
1


In [55]:
# Random array of shape (3, 3) with values between 0 and 1
random_array = np.random.rand(3, 3)

# Random integers between 1 and 10 in a 1D array of size 5
random_integers = np.random.randint(1, 10, 5)

print(random_array)
print(random_integers)

[[0.45522109 0.70432151 0.93972231]
 [0.92237919 0.39743709 0.71843598]
 [0.07031531 0.61322473 0.30941552]]
[1 2 6 1 3]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Concatenation along a single axis
concat_arr = np.concatenate((a, b))

# Stacking vertically and horizontally
a2d = np.array([[1, 2, 3]])
b2d = np.array([[4, 5, 6]])

v_stack = np.vstack((a2d, b2d))    # Vertical stacking
h_stack = np.hstack((a2d, b2d))    # Horizontal stacking

print(concat_arr)
print(v_stack)
print(h_stack)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5 6]]


In [13]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))           # Sum of all elements
print(np.prod(arr))          # Product of all elements
print(np.cumsum(arr))        # Cumulative sum
print(np.cumprod(arr))       # Cumulative product

15
120
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [19]:
# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.dot(a, b))

# Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.matmul(mat1, mat2))

# Inverse of a matrix
print(np.linalg.inv(mat1))

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(mat1)

32
[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [21]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[arr > 5])           # Elements greater than 5
print(arr[(arr % 2) == 0])    # Even elements

[6 7 8 9]
[2 4 6 8]


In [33]:
arr5 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(arr5[arr5 >= 14])
print(arr5[(arr5 % 2) == 0])

[14 15 16 17 18 19 20]
[10 12 14 16 18 20]


In [35]:
# Save array to a .npy file
np.save("my_array.npy", arr)

# Load array from a .npy file
loaded_arr = np.load("my_array.npy")

In [37]:
print(loaded_arr)

[1 2 3 4 5 6 7 8 9]
